create table "public"."foobar" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now()
);


alter table "public"."foobar" enable row level security;

CREATE UNIQUE INDEX foobar_pkey ON public.foobar USING btree (id);

alter table "public"."foobar" add constraint "foobar_pkey" PRIMARY KEY using index "foobar_pkey";


